version: '3.8'

services:
  jupyter:
    build:
      context: ./docker
      dockerfile: Dockerfile.jupyter
    container_name: jupyter
    ports:
      - '8888:8888'
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    volumes:
      - './notebook:/home/jovyan/work'
      - './data:/home/jovyan/work/data'
    networks:
      - mlflow


  mlflow-web:
    build:
      context: ./docker
      dockerfile: Dockerfile.mlflow
    container_name: mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - ./mlruns:/mlflow/mlruns
    ports:
      - '5000:5000'
    networks:
      - mlflow
    # command: ["mlflow", "server", "--backend-store-uri", "file:/mlflow/mlruns", "--default-artifact-root", "/mlflow/mlruns", "--host", "0.0.0.0"]


networks:
  mlflow: